<?php 

ob_start();
?>

<h1> TESTANDOTESTANDOTESTANDOTESTANDOTESTANDOTESTANDO </h1>
<h2> TESTANDOTESTANDOTESTANDOTESTANDOTESTANDOTESTANDO </h2>
<h3> TESTANDO TESTANDOTESTANDOTESTANDOTESTANDOTESTANDO</h3>
<h4> TESTANDOTESTANDOTESTANDOTESTANDOTESTANDOTESTANDO </h4>
<h5> TESTANDO TESTANDOTESTANDOTESTANDOTESTANDOTESTANDO</h5>
<h1> TESTANDO TESTANDOTESTANDOTESTANDOTESTANDOTESTANDO</h1>
<h2> TESTANDOTESTANDOTESTANDOTESTANDOTESTANDOTESTANDO </h2>
<h3> TESTANDOTESTANDOTESTANDOTESTANDOTESTANDOTESTANDO </h3>
<h4> TESTANDO </h4>
<h5> TESTANDO </h5>

<?php 
$html=ob_get_contents();
ob_end_clean();

require 'vendor/autoload.php';

$mpdf= new mpdf();

$mpdf->WriteHTML($html);
$mpdf->Output('arquivo.pdf','I');

?>
